<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '6.5.25',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'CU',
  'author' => 'rajesh patidar',
  'description' => 'Tracking Panda Doc Document',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'panda_doc',
  'published_date' => '2021-01-08 06:34:46',
  'type' => 'module',
  'version' => 3.0,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'panda_doc',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'CU_Panda_Doc',
      'class' => 'CU_Panda_Doc',
      'path' => 'modules/CU_Panda_Doc/CU_Panda_Doc.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/cu_panda_doc_aos_contracts_AOS_Contracts.php',
      'to_module' => 'AOS_Contracts',
    ),
  ),
  'administration' => array(
        array(
           'from' => '<basepath>/Administration/Extension/modules/Administration/Ext/Administration/panda.php',
        )
    ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/cu_panda_doc_aos_contractsMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/metadata/aos_quotes_cu_panda_doc_1MetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/CU_Panda_Doc',
      'to' => 'modules/CU_Panda_Doc',
    ),
    1 => array(
            'from' => '<basepath>/Administration/SugarModules/modules/Administration/panda.php',
            'to' => 'custom/modules/Administration/panda.php',
        ),
    2 => array(
        'from' => '<basepath>/Administration/SugarModules/modules/Administration/panda.tpl',
        'to' => 'custom/modules/Administration/panda.tpl',
    ),
    3 => array(
        'from' => '<basepath>/Administration/SugarModules/modules/Administration/Pandacallback.php',
        'to' => 'custom/modules/Administration/Pandacallback.php',
    ), 
    4 => array(
        'from' => '<basepath>/Administration/SugarModules/modules/Administration/pandacallback.php',
        'to' => 'pandacallback.php',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/AOS_Contracts/Ext/LogicHooks/Logichooks.php',
      'to' => 'custom/Extension/modules/AOS_Contracts/Ext/LogicHooks/Logichooks.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Contracts/LogicHooks/pandadoc.php',
      'to' => 'custom/modules/AOS_Contracts/LogicHooks/pandadoc.php',
    ),
     7 => array(
        'from' => '<basepath>/SugarModules/Extension/modules/CU_Panda_Doc/Pandadoc.php',
        'to' => 'custom/modules/CU_Panda_Doc/Pandadoc.php',
    ),
     8 => array(
        'from' => '<basepath>/SugarModules/Extension/modules/CU_Panda_Doc/Pandawebhook.php',
        'to' => 'Pandawebhook.php',
    ),
     9 => array(
        'from' => '<basepath>/SugarModules/Extension/modules/AOS_Contracts/Pandaredirect.php',
        'to' => 'custom/modules/AOS_Contracts/Pandaredirect.php',
    ),
      10 => array(
        'from' => '<basepath>/SugarModules/Extension/modules/AOS_Quotes/Ext/LogicHooks/Logichooks.php',
        'to' => 'custom/Extension/modules/AOS_Quotes/Ext/LogicHooks/Logichooks.php',
    ),
       11 => array(
        'from' => '<basepath>/SugarModules/modules/AOS_Quotes/LogicHooks/quotespandadoc.php',
        'to' => 'custom/modules/AOS_Quotes/LogicHooks/quotespandadoc.php',
    ),
       12 => array(
        'from' => '<basepath>/SugarModules/modules/AOS_Quotes/QuotePandaredirect.php',
        'to' => 'custom/modules/AOS_Quotes/QuotePandaredirect.php',
    ),
       13 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/CU_Panda_Doc/metadata/detailviewdefs.php',
      'to' => 'custom/modules/CU_Panda_Doc/metadata/detailviewdefs.php',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/CU_Panda_Doc/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/CU_Panda_Doc/metadata/detailviewdefs.php',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/CU_Panda_Doc/metadata/editviewdefs.php',
      'to' => 'custom/modules/CU_Panda_Doc/metadata/editviewdefs.php',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/CU_Panda_Doc/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/CU_Panda_Doc/metadata/editviewdefs.php',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/relationships/vardefs/aos_quotes_cu_panda_doc_1_AOS_Quotes.php',
      'to' => 'custom/Extension/modules/relationships/vardefs/aos_quotes_cu_panda_doc_1_AOS_Quotes.php',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/relationships/vardefs/aos_quotes_cu_panda_doc_1_CU_Panda_Doc.php',
      'to' => 'custom/Extension/modules/relationships/vardefs/aos_quotes_cu_panda_doc_1_CU_Panda_Doc.php',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/relationships/layoutdefs/aos_quotes_cu_panda_doc_1_AOS_Quotes.php',
      'to' => 'custom/Extension/modules/relationships/layoutdefs/aos_quotes_cu_panda_doc_1_AOS_Quotes.php',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/relationships/relationships/aos_quotes_cu_panda_doc_1MetaData.php',
      'to' => 'custom/Extension/modules/relationships/relationships/aos_quotes_cu_panda_doc_1MetaData.php',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/CU_Panda_Doc/Ext/Vardefs/aos_quotes_cu_panda_doc_1_CU_Panda_Doc.php',
      'to' => 'custom/Extension/modules/CU_Panda_Doc/Ext/Vardefs/aos_quotes_cu_panda_doc_1_CU_Panda_Doc.php',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/CU_Panda_Doc/Ext/Language/en_us.customaos_quotes_cu_panda_doc_1.php',
      'to' => 'custom/Extension/modules/CU_Panda_Doc/Ext/Language/en_us.customaos_quotes_cu_panda_doc_1.php',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/CU_Panda_Doc/Ext/Language/en_us.panda_doc.php',
      'to' => 'custom/Extension/modules/CU_Panda_Doc/Ext/Language/en_us.panda_doc.php',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/AOS_Quotes/Ext/Vardefs/aos_quotes_cu_panda_doc_1_AOS_Quotes.php',
      'to' => 'custom/Extension/modules/AOS_Quotes/Ext/Vardefs/aos_quotes_cu_panda_doc_1_AOS_Quotes.php',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/AOS_Quotes/Ext/Language/en_us.customaos_quotes_cu_panda_doc_1.php',
      'to' => 'custom/Extension/modules/AOS_Quotes/Ext/Language/en_us.customaos_quotes_cu_panda_doc_1.php',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/AOS_Quotes/Ext/Layoutdefs/aos_quotes_cu_panda_doc_1_AOS_Quotes.php',
      'to' => 'custom/Extension/modules/AOS_Quotes/Ext/Layoutdefs/aos_quotes_cu_panda_doc_1_AOS_Quotes.php',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/AOS_Quotes/Ext/Layoutdefs/_overrideAOS_Quotes_subpanel_aos_quotes_cu_panda_doc_1.php',
      'to' => 'custom/Extension/modules/AOS_Quotes/Ext/Layoutdefs/_overrideAOS_Quotes_subpanel_aos_quotes_cu_panda_doc_1.php',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Contracts/metadata/detailviewdefs.php',
      'to' => 'custom/modules/AOS_Contracts/metadata/detailviewdefs.php',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Contracts/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/AOS_Contracts/metadata/detailviewdefs.php',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Contracts/metadata/editviewdefs.php',
      'to' => 'custom/modules/AOS_Contracts/metadata/editviewdefs.php',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Contracts/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/AOS_Contracts/metadata/editviewdefs.php',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Contracts/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/AOS_Contracts/metadata/quickcreatedefs.php',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Contracts/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/AOS_Contracts/metadata/quickcreatedefs.php',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Contracts/metadata/searchdefs.php',
      'to' => 'custom/modules/AOS_Contracts/metadata/searchdefs.php',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Contracts/metadata/searchdefs.php',
      'to' => 'custom/working/modules/AOS_Contracts/metadata/searchdefs.php',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/AOS_Contracts/Ext/Vardefs/_override_sugarfield_global_tax_c.php',
      'to' => 'custom/Extension/modules/AOS_Contracts/Ext/Vardefs/_override_sugarfield_global_tax_c.php',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/AOS_Contracts/Ext/Vardefs/cu_custom_services_contract_aos_contracts_AOS_Contracts.php',
      'to' => 'custom/Extension/modules/AOS_Contracts/Ext/Vardefs/cu_custom_services_contract_aos_contracts_AOS_Contracts.php',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/AOS_Contracts/Ext/Vardefs/cu_panda_doc_aos_contracts_AOS_Contracts.php',
      'to' => 'custom/Extension/modules/AOS_Contracts/Ext/Vardefs/cu_panda_doc_aos_contracts_AOS_Contracts.php',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/AOS_Contracts/Ext/Vardefs/cu_contract_charging_metrics_aos_contracts_AOS_Contracts.php',
      'to' => 'custom/Extension/modules/AOS_Contracts/Ext/Vardefs/cu_contract_charging_metrics_aos_contracts_AOS_Contracts.php',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/AOS_Contracts/Ext/Language/en_us.Contract_Charging_Metrics.php',
      'to' => 'custom/Extension/modules/AOS_Contracts/Ext/Language/en_us.Contract_Charging_Metrics.php',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/AOS_Contracts/Ext/Language/en_us.panda_doc.php',
      'to' => 'custom/Extension/modules/AOS_Contracts/Ext/Language/en_us.panda_doc.php',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/AOS_Contracts/Ext/Language/en_us.Custom_Services_Contract.php',
      'to' => 'custom/Extension/modules/AOS_Contracts/Ext/Language/en_us.Custom_Services_Contract.php',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/AOS_Contracts/Ext/Layoutdefs/cu_panda_doc_aos_contracts_AOS_Contracts.php',
      'to' => 'custom/Extension/modules/AOS_Contracts/Ext/Layoutdefs/cu_panda_doc_aos_contracts_AOS_Contracts.php',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Quotes/metadata/detailviewdefs.php',
      'to' => 'custom/modules/AOS_Quotes/metadata/detailviewdefs.php',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Quotes/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/AOS_Quotes/metadata/detailviewdefs.php',
    ),
    46 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Quotes/metadata/editviewdefs.php',
      'to' => 'custom/modules/AOS_Quotes/metadata/editviewdefs.php',
    ),
    47 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Quotes/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/AOS_Quotes/metadata/editviewdefs.php',
    ),
    48 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Quotes/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/AOS_Quotes/metadata/quickcreatedefs.php',
    ),
    49 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Quotes/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/AOS_Quotes/metadata/quickcreatedefs.php',
    ),
    50 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Quotes/metadata/searchdefs.php',
      'to' => 'custom/modules/AOS_Quotes/metadata/searchdefs.php',
    ),
    51 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Quotes/metadata/searchdefs.php',
      'to' => 'custom/working/modules/AOS_Quotes/metadata/searchdefs.php',
    ),
    52 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/AOS_Quotes/Ext/Vardefs/_override_sugarfield_global_tax_c.php',
      'to' => 'custom/Extension/modules/AOS_Quotes/Ext/Vardefs/_override_sugarfield_global_tax_c.php',
    ),
    53 => 
    array (
     'from' => '<basepath>/SugarModules/modules/AOS_Products_Quotes/line_items.js',
      'to' => 'custom/modules/AOS_Products_Quotes/line_items.js',
    ),
    54 => 
    array (
     'from' => '<basepath>/SugarModules/themes/SuiteP/include/DetailView/DetailView.tpl',
      'to' => 'custom/themes/SuiteP/include/DetailView/DetailView.tpl',
    ),
    55 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/AOS_Contracts/Ext/Language/en_us.lang.php',
      'to' => 'custom/Extension/modules/AOS_Contracts/Ext/Language/en_us.lang.php',
    ),
    56 => 
    array (
      'from' => '<basepath>/SugarModules/Extension/modules/AOS_Quotes/Ext/Language/en_us.lang.php',
      'to' => 'custom/Extension/modules/AOS_Quotes/Ext/Language/en_us.lang.php',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/CU_Panda_Doc.php',
      'to_module' => 'CU_Panda_Doc',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/AOS_Contracts.php',
      'to_module' => 'AOS_Contracts',
      'language' => 'en_us',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
     3 =>
     array(
            'from' => '<basepath>/Administration/Extension/modules/Administration/Ext/Language/en_us.panda.php',
            'to_module' => 'Administration',
            'language' =>'en_us'
        ),
     4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Quotes/language/en_us.lang.php',
      'to_module' => 'AOS_Quotes',
      'language' => 'en_us',
    ),
    5=>
    array (
      'from' => '<basepath>/SugarModules/include/language/en_us.conttract_update.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/AOS_Contracts/language/en_us.lang.php',
      'to_module' => 'AOS_Contracts',
      'language' => 'en_us',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/en_us.quote_update.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/cu_panda_doc_aos_contracts_CU_Panda_Doc.php',
      'to_module' => 'CU_Panda_Doc',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/cu_panda_doc_aos_contracts_AOS_Contracts.php',
      'to_module' => 'AOS_Contracts',
    ),
  ),
  'entrypoints' => array (
        0 => array (
            'from' => '<basepath>/Administration/SugarModules/EntryPointRegistry/Pandacallback.php',
            'to_module' => 'custom/Extension/application/Ext/EntryPointRegistry/Pandacallback.php',
        ),
        1 => array (
            'from' => '<basepath>/SugarModules/EntryPointRegistry/Pandadoc.php',
            'to_module' => 'custom/Extension/application/Ext/EntryPointRegistry/Pandadoc.php',
        ),
        2 => array (
            'from' => '<basepath>/SugarModules/EntryPointRegistry/Pandaredirect.php',
            'to_module' => 'custom/Extension/application/Ext/EntryPointRegistry/Pandaredirect.php',
        ),
        3 => array (
            'from' => '<basepath>/SugarModules/EntryPointRegistry/QuotePandaredirect.php',
            'to_module' => 'custom/Extension/application/Ext/EntryPointRegistry/QuotePandaredirect.php',
        ),
    ),
  'custom_fields' => 
  array (
    'AOS_Contractsglobal_tax_c' => 
    array (
      'id' => 'AOS_Contractsglobal_tax_c',
      'name' => 'global_tax_c',
      'label' => 'LBL_GLOBAL_TAX',
      'comments' => '',
      'help' => '',
      'module' => 'AOS_Contracts',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2020-11-27 06:57:46',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'global_vat_list',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'AOS_Quotesglobal_tax_c' => 
    array (
      'id' => 'AOS_Quotesglobal_tax_c',
      'name' => 'global_tax_c',
      'label' => 'LBL_GLOBAL_TAX_C',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'AOS_Quotes',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2020-11-27 15:47:51',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'global_vat_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
);