<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '6.5.25',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => '',
  'author' => 'raj',
  'description' => 'Whatsapp link ',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Lead_whatsapp_field',
  'published_date' => '2020-12-12 05:33:31',
  'type' => 'module',
  'version' => 1,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Lead_whatsapp_field',
  'relationships' => 
  array (
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/en_us.Lead_whatsapp_field.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Leads/language/en_us.lang.php',
      'to_module' => 'Leads',
      'language' => 'en_us',
    ),
  ),
  'custom_fields' => 
  array (
    'Leadswhatsapp_mobile_no_c' => 
    array (
      'id' => 'Leadswhatsapp_mobile_no_c',
      'name' => 'whatsapp_mobile_no_c',
      'label' => 'LBL_WHATSAPP_MOBILE_NO',
      'comments' => '',
      'help' => '',
      'module' => 'Leads',
      'type' => 'Whatsapp',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '',
      'date_modified' => '2020-12-12 05:26:59',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/include/SugarFields/Fields/Whatsapp/DetailView.tpl',
      'to' => 'custom/include/SugarFields/Fields/Whatsapp/DetailView.tpl',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/DynamicFields/templates/Fields/TemplateWhatsapp.php',
      'to' => 'custom/modules/DynamicFields/templates/Fields/TemplateWhatsapp.php',
    ),
     2 => 
    array (
      'from' => '<basepath>/Extension/modules/ModuleBuilder/Ext/Language/en_us.Whatsapp.php',
      'to' => 'custom/Extension/modules/ModuleBuilder/Ext/Language/en_us.Whatsapp.php',
    ),
  ),
  'layoutfields' => array(
        array(
            'additional_fields' =>
            array(
                'Leads' => 'whatsapp_mobile_no_c',
            ),
        ),
   ),
);